# .goreleaser.yml
version: 2
project_name: tufie

before:
  hooks:
    - go mod tidy
    - go generate ./...

build:
  env:
    - CGO_ENABLED=0
  main: ./
  targets:
    - linux_amd64
    - linux_arm64
    - windows_amd64
    - windows_arm64
    - darwin_amd64
    - darwin_arm64

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip

brew:
  homepage: "https://github.com/kairoaraujo/tufie"
  description: "TUFie an Open Source generic TUF client"
  folder: Formula
  commit_author:
    name: kairoaraujo
    email: kairo@dearaujo.nl
  repository:
    owner: kairoaraujo
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  test: |
    system "#{bin}/tufie --help"

winget:
  name: tufie
  publisher: kairoaraujo
  license: MIT
  license_url: "https://github.com/kairoaraujo/tufie/blob/master/LICENSE"
  copyright: "Kairo de Araujo"
  homepage: "https://github.com/kairoaraujo/tufie"
  short_description: "TUFie an Open Source generic TUF client"
  publisher_support_url: "https://github.com/kairoaraujo/tufie/issues/new"
  package_identifier: "kairoaraujo.tufie"
  url_template: "https://github.com/kairoaraujo/tufie/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  skip_upload: auto
  release_notes: "{{ .Changelog }}"
  tags:
    - golang
    - cli
  commit_author:
    name: kairoaraujo
    email: kairo@dearaujo.nl
  goamd64: v1
  repository:
    owner: kairoaraujo
    name: winget-pkgs
    branch: "tufie-{{ .Version }}"
    token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
    pull_request:
      enabled: true
      draft: true
      base:
        owner: microsoft
        name: winget-pkgs
        branch: master

source:
  enabled: true

changelog:
  sort: asc
  use: github

sbom:
  artifacts: archive

release:
  prerelease: auto
  github:
    owner: kairoaraujo
    name: tufie

sign:
  cmd: cosign
  args:
    - "sign-blob"
    - "--output-signature=${signature}"
    - "${artifact}"
    - "--yes"
  artifacts: archive
  output: true
