name: Lint and Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.21.x]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup - Go ${{ matrix.go-version }}
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d

  checks:
    name: Checks and linters
    strategy:
      matrix:
        go-version: [1.21.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: golangci-lint
        uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
        with:
          version: latest
          args: --timeout 5m --verbose
      - name: govulncheck
        uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4
        with:
          go-version-input: ${{ matrix.go-version }}
          go-package: ./...