name: Lint and Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.24.x]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup - Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574

  checks:
    name: Checks and linters
    strategy:
      matrix:
        go-version: [1.24.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84
        with:
          version: latest
          args: --timeout 5m --verbose
      - name: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee
        with:
          go-version-input: ${{ matrix.go-version }}
          go-package: ./...